# Site settings
title: Antiques.bz
email: info@antiques.bz
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Antiques.bz
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://antiques.bz" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
